spring.application.name=authentication-service
# =========================
# Application de base
# =========================
server.port=8081

# =========================
# MongoDB (dev local)
# =========================
#   MONGO_INITDB_ROOT_USERNAME=mongo_root
#   MONGO_INITDB_ROOT_PASSWORD=mongo_password
#   MONGO_INITDB_DATABASE=auth_db
#
#
spring.mongodb.uri=mongodb://mongo_root:mongo_password@localhost:27017/auth_db?authSource=admin

# =========================
# JWT
# =========================
# Clé secrète pour signer les tokens
app.security.jwt.secret=7f1b4c8e9a2d5F!9Q3zL7kP@2vX6nR8sT4yW0mB1hD5gJ9

# Durée de vie du token (en ms) : 1h
app.security.jwt.expiration=3600000

# Durée de vie du refresh token (en ms) : 30 jours
app.security.jwt.refresh-expiration=2592000000

# =========================
# Logs
# =========================
logging.level.root=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO

# =========================
# Timezone / Locale
# =========================
spring.jackson.time-zone=UTC
spring.jackson.locale=fr_FR


# Reset password
app.security.password-reset.master-code=DEV_SUPER_RESET_123
app.security.password-reset.expiration-minutes=15

# Kafka (exemple)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

app.kafka.password-reset-topic=password-reset-requests
