services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clouddelivery-jenkins-local
    restart: unless-stopped
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - maven_cache:/root/.m2          # cache Maven — évite de retélécharger à chaque build
      - ./casc:/var/jenkins_casc:ro
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_casc

volumes:
  jenkins_home:
  maven_cache:
