spring.application.name=order-service
server.port=8083

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cld_main_db
spring.datasource.username=cld_user
spring.datasource.password=cld_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Kafka Producer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Kafka Topics
app.kafka.order-confirmed-topic=order-confirmed
app.kafka.order-cancelled-topic=order-cancelled

# Logging
logging.level.root=INFO
logging.level.org.example.orderservice=DEBUG
